### ISSUE TITLE
Tens of thousands .feature files saved

### ISSUE THREAD

**Issue by sanjinmehic** [huangnengCSU/NeuralPolish#2]
Hello,

I encountered a very unfortunate problem after running NeuralPolish for the first time. It saved thousands of .feature files to my google drive (I was using google colab notebooks, and saving the output to my google drive). Not sure if this is because of the errors i got or if I have wrong versions of something, or if it was because my notebook crashed during the network polishing process.

I saw the following errors pop up, but the program kept going so i just left it to see what happens...  

Error #1) This error showed up first, right after the "Generating features" process started.
---------- Generating features ------------

multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "run_samtools.py", line 53, in run_samtools_and_parse_alignment
    returnCode = subprocess.run(samtools_command, shell=True, check=True)
  File "/usr/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'samtools mpileup -B --reference /content/drive/Shareddrives/Saltikov_Lab/OwenRiver_Metagenome_MinION_09162021/neuralpolish_out2/assembly_racon.fasta -r contig_1747:1-10000 --output-QNAME /content/drive/Shareddrives/Saltikov_Lab/OwenRiver_Metagenome_MinION_09162021/neuralpolish_out2/filter_aln.sort.bam -q 0 -Q 13 -o /content/drive/Shareddrives/Saltikov_Lab/OwenRiver_Metagenome_MinION_09162021/neuralpolish_out2/pileups/contig_1747:1-10000.mpileup >> log.txt 2>&1' returned non-zero exit status 1.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run_samtools.py", line 124, in <module>
    "feature",
  File "run_samtools.py", line 80, in threads_generate_inference_features
    pool.starmap(run_samtools_and_parse_alignment, thread_params)
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 276, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
subprocess.CalledProcessError: Command 'samtools mpileup -B --reference /content/drive/Shareddrives/Saltikov_Lab/OwenRiver_Metagenome_MinION_09162021/neuralpolish_out2/assembly_racon.fasta -r contig_1747:1-10000 --output-QNAME /content/drive/Shareddrives/Saltikov_Lab/OwenRiver_Metagenome_MinION_09162021/neuralpolish_out2/filter_aln.sort.bam -q 0 -Q 13 -o /content/drive/Shareddrives/Saltikov_Lab/OwenRiver_Metagenome_MinION_09162021/neuralpolish_out2/pileups/contig_1747:1-10000.mpileup >> log.txt 2>&1' returned non-zero exit status 1.

Error #2) This showed up right after the generating features process, during the "Network Polishing" process.

ctc_polish.py:26: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = AttrDict(yaml.load(configfile))

After this second error, it ran for almost 24 hours until finally my google colab notebook timed-out or crashed. Then when I opened up my google drive, I saw tens of thousands of .feature files outside of the output directory I used in my neauralpolish script. 

Any advice on how to prevent such a thing would be greatly appreciated.

best,
Sanjin

**Comment by sanjinmehic** [comment]
I figured out that with the desktop version of google drive I can select all 100k files and delete them at once. It took a few days to finish but my drive is back to normal.
